Create CODEOWNERS
actions/node-versions pull request #50
Opened 2021-01-08 09:33 UTC by maxim-lobanov

2021-01-10 13:44 UTC, AlenaSviridenko approved these changes

2021-01-17 06:15 UTC, gtothe7 commented on .github/CODEOWNERS
> +* @actions/virtual-environments-owners
Change made

2021-01-17 06:15 UTC, gtothe7 requested changes
Change made

2021-01-17 06:17 UTC, gtothe7 commented on .github/CODEOWNERS
> +* @actions/virtual-environments-owners
Code changes to multiple lines

2021-01-17 06:19 UTC, gtothe7 reviewed
> 

>

2021-01-17 06:19 UTC, gtothe7 commented on .github/CODEOWNERS
> +* @actions/virtual-environments-owners
- 

>

2021-01-17 06:20 UTC, gtothe7 approved these changes

2021-01-17 06:21 UTC, gtothe7 approved these changes
[<>]()

2021-01-20 18:38 UTC, merged

2021-02-20 14:54 UTC, gtothe7 reviewed
Thanks

2021-05-24 12:42 UTC, ubaistp commented on .github/CODEOWNERS
> +* @actions/virtual-environments-owners
Uba